feat: set the length of the historical message
anse-app/anse pull request #75
Opened 2023-06-26 07:18 UTC by chancelyg

### Description
Added a button for setting the length of historical messages, and correctly calculates the length of the current user's historical messages upon submission to avoid triggering the MaxTokens error. 

This enhancement greatly improves usability.
### Linked Issues

### Additional context

2023-06-26 09:50 UTC, yzh990918 approved these changes

2023-06-26 09:51 UTC, yzh990918 requested changes
If write this, maxTokens will be negative.

2023-06-28 02:14 UTC, chancelyg commented
Apologies, I have revised the computation rules for MaxTokens, ensuring that it will no longer yield negative values.

2023-06-28 09:33 UTC, yzh990918 approved these changes

2023-06-28 09:36 UTC, yzh990918 commented
Thanks!

2023-06-28 09:36 UTC, merged